name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: SIT.Manager
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }} --platform ${{ matrix.platform }}
