name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: SIT.Manager
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Check .NET SDK version
      run: dotnet --list-sdks
    - name: Restore project
      run: dotnet restore
    - name: Check ENV
      run: dir C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\8.0.201\\Microsoft\VisualStudio\v17.0\AppxPackage\
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }}
